CREATE DATABASE bookstore;

USE bookstore;

CREATE TABLE PRODUCTS(
	PID INT PRIMARY KEY AUTO_INCREMENT,
    PNAME VARCHAR(100) NOT NULL,
    PIMAGE LONGBLOB NOT NULL,
    PGENERE VARCHAR(20) NOT NULL,
    PAPRICE INT NOT NULL DEFAULT 0,
    PDPRICE INT NOT NULL DEFAULT 0,
    PQUANTITY INT NOT NULL DEFAULT 1
);
select* FROM PRODUCTS
CREATE TABLE USERS(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(120) NOT NULL,
    USER_MOBILE VARCHAR(12) NOT NULL,
    USER_PASSWORD VARCHAR(100) NOT NULL
);
select* FROM USERS
CREATE TABLE CART(
	USER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT
);


